#!/usr/bin/env bash
# Print, install, or remove the bash completion for this repository.
#
# `just --completions bash` completes recipe names only. This completion also
# completes the arguments: the host names, the roles, and the project names.
#
#   bash-completion.sh print       write the script to the standard output
#   bash-completion.sh install     write it to the user completion directory
#   bash-completion.sh uninstall   delete that file
#
# The install action prints the path of the file, so this works:
#
#   source "$(just bash-completion-install)"

set -euo pipefail
# shellcheck source=scripts/lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

action="${1:-print}"

# The bash-completion package reads the file whose name is the command.
dest_dir="${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion/completions"
dest="$dest_dir/just"

# emit: print the completion script.
#
# The quoted here-document marker stops every expansion, so the text below goes
# out exactly as it is written.
emit() {
	cat <<'COMPLETION'
# bash completion for just, with the arguments of palette-edge-libvirt.
#
# This file completes the recipe names of any justfile. It completes the
# arguments only in the palette-edge-libvirt checkout, so it is safe as the
# completion for every project.
#
# Generated by: just bash-completion

# _pel_lab: the LAB_NAME of the current checkout.
_pel_lab() { just --evaluate lab 2>/dev/null; }

# _pel_root: the directory of the current justfile.
_pel_root() { just --evaluate root 2>/dev/null; }

# _pel_domains: the libvirt domains of this lab.
_pel_domains() {
    local lab
    lab="$(_pel_lab)" || return 0
    [ -n "$lab" ] || return 0
    virsh list --all --name 2>/dev/null | grep "^${lab}-" || true
}

# _pel_nodes: the node names that the topology defines, and the domains that
# already exist. `just seed` and `just host-up` accept a name that has no
# domain yet, so both sets are useful.
_pel_nodes() {
    local lab control worker i
    lab="$(_pel_lab)" || return 0
    [ -n "$lab" ] || return 0
    control="$(just --evaluate control_count 2>/dev/null)"
    worker="$(just --evaluate worker_count 2>/dev/null)"
    for ((i = 1; i <= ${control:-0}; i++)); do printf '%s-cp-%s\n' "$lab" "$i"; done
    for ((i = 1; i <= ${worker:-0}; i++)); do printf '%s-wk-%s\n' "$lab" "$i"; done
    _pel_domains
}

# _pel_projects: the projects that have an environment file.
_pel_projects() {
    local root file
    root="$(_pel_root)" || return 0
    [ -d "$root/envs" ] || return 0
    for file in "$root"/envs/*.env; do
        [ -e "$file" ] || continue
        basename "$file" .env
    done
}

_pel_just_complete() {
    local cur recipe
    cur="${COMP_WORDS[COMP_CWORD]}"
    COMPREPLY=()

    # The first word after `just` is the recipe name. This works for every
    # justfile, not only for this repository.
    if [ "$COMP_CWORD" -eq 1 ]; then
        mapfile -t COMPREPLY < <(compgen -W "$(just --summary 2>/dev/null)" -- "$cur")
        return 0
    fi

    recipe="${COMP_WORDS[1]}"

    # Complete the arguments only in this repository. A different justfile can
    # use the same recipe name for a different purpose, and this test keeps
    # these values out of it.
    just --summary 2>/dev/null | tr ' ' '\n' | grep -qx palette-hosts || return 0

    case "$recipe" in
    console | host-down | host-eject | host-status | ip)
        mapfile -t COMPREPLY < <(compgen -W "$(_pel_domains)" -- "$cur")
        ;;
    host-up)
        if [ "$COMP_CWORD" -eq 2 ]; then
            mapfile -t COMPREPLY < <(compgen -W "$(_pel_nodes)" -- "$cur")
        else
            mapfile -t COMPREPLY < <(compgen -W "control worker" -- "$cur")
        fi
        ;;
    seed)
        mapfile -t COMPREPLY < <(compgen -W "$(_pel_nodes)" -- "$cur")
        ;;
    adopt-project | default-project | remove-project)
        mapfile -t COMPREPLY < <(compgen -W "$(_pel_projects)" -- "$cur")
        ;;
    esac
    return 0
}

complete -F _pel_just_complete just
COMPLETION
}

case "$action" in
print)
	emit
	;;
install)
	mkdir -p "$dest_dir"
	emit >"$dest"
	# The path goes to the standard output, and the messages go to the
	# standard error. `source "$(just bash-completion-install)"` then works.
	info "installed the completion at $dest" >&2
	info "bash reads it at the next login. For this shell now:" >&2
	printf '    source %s\n' "$dest" >&2
	printf '%s\n' "$dest"
	;;
uninstall)
	if [ -f "$dest" ]; then
		rm -f "$dest"
		info "removed $dest"
	else
		skip "there is no completion file at $dest"
	fi
	;;
*)
	die "unknown action '$action'. Use print, install, or uninstall."
	;;
esac
