#!/usr/bin/env bash
# Print, install, or remove the bash completion for this repository.
#
# `just --completions bash` completes recipe names only. This completion also
# completes the arguments.
#
# The completion reads the recipes and their parameters from `just` itself. It
# holds no list of recipe names. A new recipe with a parameter called `host`
# therefore completes host names with no change to this file. See the kinds
# below.
#
#   bash-completion.sh print       write the script to the standard output
#   bash-completion.sh install     write it to the user completion directory
#   bash-completion.sh uninstall   delete that file
#
# The install action prints the path of the file, so this works:
#
#   source "$(just bash-completion-install)"

set -euo pipefail
# shellcheck source=scripts/lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

action="${1:-print}"

# The bash-completion package reads the file whose name is the command.
dest_dir="${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion/completions"
dest="$dest_dir/just"

# emit: print the completion script.
#
# The quoted here-document marker stops every expansion, so the text below goes
# out exactly as it is written.
emit() {
	cat <<'COMPLETION'
# bash completion for just, with the arguments of palette-edge-libvirt.
#
# This file completes the recipe names of any justfile. It completes the
# arguments only in the palette-edge-libvirt checkout, so it is safe as the
# completion for every project.
#
# Generated by: just bash-completion

# ANCHOR: kinds
# The kinds of argument that this completion understands. A recipe parameter
# takes its name from the kind of value it holds, not from its position, so
# this list does not grow when a recipe is added.
#
#   host          a libvirt domain of this lab, or a node of the topology
#   project       a project that has an environment file
#   role          control or worker
#
# _PEL_KINDS_FREE names the parameters that hold free text. They get no
# completion on purpose.
_PEL_KINDS="host project role"
_PEL_KINDS_FREE="description"
# ANCHOR_END: kinds

# _pel_lab: the LAB_NAME of the current checkout.
_pel_lab() { just --evaluate lab 2>/dev/null; }

# _pel_param RECIPE INDEX: print the name of one parameter of a recipe.
# `just` is the source of this, so the completion never holds a recipe name.
_pel_param() {
    just --dump --dump-format json 2>/dev/null |
        PEL_RECIPE="$1" PEL_INDEX="$2" python3 -c '
import json, os, sys
try:
    data = json.load(sys.stdin)
except Exception:
    sys.exit(0)
recipe = (data.get("recipes") or {}).get(os.environ["PEL_RECIPE"])
if not recipe:
    sys.exit(0)
params = recipe.get("parameters") or []
index = int(os.environ["PEL_INDEX"])
if 0 <= index < len(params):
    print(params[index]["name"])
' 2>/dev/null
}

# _pel_domains: the libvirt domains of this lab.
_pel_domains() {
    local lab
    lab="$(_pel_lab)" || return 0
    [ -n "$lab" ] || return 0
    virsh list --all --name 2>/dev/null | grep "^${lab}-" || true
}

# _pel_nodes: the node names of the topology, and the domains that exist.
# `just seed` and `just host-up` accept a name that has no domain yet, so both
# sets are useful.
_pel_nodes() {
    local lab control worker i
    lab="$(_pel_lab)" || return 0
    [ -n "$lab" ] || return 0
    control="$(just --evaluate control_count 2>/dev/null)"
    worker="$(just --evaluate worker_count 2>/dev/null)"
    {
        for ((i = 1; i <= ${control:-0}; i++)); do printf '%s-cp-%s\n' "$lab" "$i"; done
        for ((i = 1; i <= ${worker:-0}; i++)); do printf '%s-wk-%s\n' "$lab" "$i"; done
        _pel_domains
    } | sort -u
}

# _pel_projects: the projects that have an environment file.
#
# The justfile owns the path, so this reads the path from the justfile. The
# files moved out of the checkout, and this function needed no other change.
_pel_projects() {
    local envs file
    envs="$(just --evaluate envs_dir 2>/dev/null)" || return 0
    [ -n "$envs" ] && [ -d "$envs" ] || return 0
    for file in "$envs"/*.env; do
        [ -e "$file" ] || continue
        basename "$file" .env
    done
}

_pel_just_complete() {
    local cur recipe kind index
    cur="${COMP_WORDS[COMP_CWORD]}"
    COMPREPLY=()

    # The first word after `just` is the recipe name. `just --summary` answers
    # for any justfile, so this part works in every project.
    if [ "$COMP_CWORD" -eq 1 ]; then
        mapfile -t COMPREPLY < <(compgen -W "$(just --summary 2>/dev/null)" -- "$cur")
        return 0
    fi

    recipe="${COMP_WORDS[1]}"

    # Complete the arguments only in this repository. A different justfile can
    # use the same parameter name for a different purpose, and this test keeps
    # these values out of it.
    just --summary 2>/dev/null | tr ' ' '\n' | grep -qx palette-hosts || return 0

    # The recipe name is word 1, so word 2 is parameter 0.
    index=$((COMP_CWORD - 2))
    kind="$(_pel_param "$recipe" "$index")"

    case "$kind" in
    host)
        mapfile -t COMPREPLY < <(compgen -W "$(_pel_nodes)" -- "$cur")
        ;;
    project)
        mapfile -t COMPREPLY < <(compgen -W "$(_pel_projects)" -- "$cur")
        ;;
    role)
        mapfile -t COMPREPLY < <(compgen -W "control worker" -- "$cur")
        ;;
    esac
    return 0
}

complete -F _pel_just_complete just
COMPLETION
}

case "$action" in
print)
	emit
	;;
install)
	mkdir -p "$dest_dir"
	emit >"$dest"
	# The path goes to the standard output, and the messages go to the
	# standard error. `source "$(just bash-completion-install)"` then works.
	info "installed the completion at $dest" >&2
	info "bash reads it at the next login. For this shell now:" >&2
	printf '    source %s\n' "$dest" >&2
	printf '%s\n' "$dest"
	;;
uninstall)
	if [ -f "$dest" ]; then
		rm -f "$dest"
		info "removed $dest"
	else
		skip "there is no completion file at $dest"
	fi
	;;
*)
	die "unknown action '$action'. Use print, install, or uninstall."
	;;
esac
